<?php

namespace AppBundle\Repository;

/**
 * SiteContactsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteContactsRepository extends \Doctrine\ORM\EntityRepository
{
}
