# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            logout: ~
            remember_me:
              secret:   '%secret%'
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
              csrf_token_generator: security.csrf.token_manager
              success_handler: authentication_handler
              failure_handler: authentication_handler

            logout_on_user_change: true

    role_hierarchy:
        ROLE_USER:
            - ROLE_USER
            - ROLE_APP_STUFF
            - ROLE_APP_ADMIN
        ROLE_ADMIN:
            - ROLE_USER
            - ROLE_APP_STUFF
            - ROLE_APP_ADMIN
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
            - ROLE_ALLOWED_TO_SWITCH

    access_control:
        - { path: ^/login$, allow_if: "is_anonymous() and !is_authenticated()" }
        - { path: ^/register, allow_if: "is_anonymous() and !is_authenticated()" }
#        - { path: ^/resetting, allow_if: "is_anonymous() and !is_authenticated()" }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/group, roles: ROLE_USER}
        - { path: ^/add_comment$, roles: ROLE_USER, method: POST}
        - { path: ^/delete_comment$, roles: ROLE_ADMIN, method: DELETE}
        - { path: ^/admin-management, roles: ROLE_ADMIN }